# Generated by Django 5.0.7 on 2024-07-25 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('recipient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bouquet_makers',
            field=models.ManyToManyField(blank=True, related_name='bouquet_makers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='drivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='recipients', to='recipient.recipient'),
        ),
    ]
