# Generated by Django 5.0.7 on 2024-07-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='group',
            field=models.IntegerField(choices=[(1, 'Group 1'), (2, 'Group 2')], default=0),
            preserve_default=False,
        ),
    ]
